### ISSUE TITLE
Switch to Organisation model?

### ISSUE THREAD

**Issue by kingsleyh** [intellij-dlanguage/intellij-dlanguage#157]
Hi, 

Would switching to an organisation model help at all with access to stuff? e.g. Travis, the repos etc? If we make an organisation what should it be called?

--K

**Comment by russel** [comment]
I think it would be good to switch to switch this project to an organisation, but mostly for marketing rather than procedural reasons. A project owned by an organisation with multiple owners gives more confidence to people about longevity.

Personally I'd go with DLanguage if that is possible since it is wonderfully wide ranging.

**Comment by SingingBush** [comment]
I'd got for the same format as the [rust plugin](https://github.com/intellij-rust/intellij-rust): *intellij-dlang* for both organisation and repo name.

**Comment by russel** [comment]
The problem with the IntelliJ-DLang name is the confusion it causes when you make the plugin usable with CLion, or any of the other JetBrains IDE that can use the plugin.

**Comment by rikkimax** [comment]
There is dlang-community (barely started) meant for maintenance purposes.
Basically people handling PR's pulling ext. when the owner is not available.

https://github.com/dlang-community

**Comment by russel** [comment]
The dlang-community seems to be a place where Hackerpilot forks are kept. Is Hackerpilot not working on the originals? The current state is a bit conflicted.

With the new GitHub owners/administrators systems hosting Dlanguage aka intellij-dlang, or whatever, is viable, but would it be the right thing to do? 

If dlang-community is a place where actively managed systems could be then the centralisation would be good for marketing. Having the umbrella of people willing to step in if a project appears to be in hiatus is also a good thing. However if the location is just a dumping ground for unwanted projects this then taints the centralisation with lots of negative vibes. In this context the current set up is workable, and more desirable. Having said this I think it would be good for this project to be organisation rather than person hosted. Nothing wrong with Kingsley's management, it is a purely marketing position: organisation owned projects are easier to "sell".

**Comment by rikkimax** [comment]
So dlang-community was created because HP was gone for a few months (very
busy to my understanding) and so PR's weren't reviewed or pulled. It does
need a charter to be written up but the general idea is active projects
that needs to be maintained long term but not enough resources to actually
go ahead and maintain it especially when life gets hectic.

**Comment by russel** [comment]
I did something similar for LiteIDE a while back, missing sole developer, backlog, etc. But the person returned and resumed local control, leaving the organisation adrift. If dlang-community is to be an umbrella organisation, and this could be a Very Good Thing™, HP need to hand over the original master to the organisation and then reclone from there. Having the organisation have a fork is giving the wrong message about ownership and mainline-ness. 

So if the organisation is simple a place for projects and project owners to locate their projects with the organisation owners only stepping in when a project appears to be in hiatus, then I think DLanguage could well get benefit from that location as well as the organisation getting benefit from DLanguage transferring there.

**Comment by RUSshy** [comment]
intellij dlang is the best one, if you google it's easy to find it

**Comment by kingsleyh** [comment]
ok I'm going to do it  - I prefer the more specific intellij-dlang like the rust plugin.

**Comment by kingsleyh** [comment]
oh the organisation - intellij-dlang already exists:   https://github.com/intellij-dlang

did someone here create it already?

**Comment by pirocks** [comment]
Perhaps its related to this: https://github.com/elendel-/intelliD
An alternative name could be intellij_dlang.

**Comment by kingsleyh** [comment]
Dunno - I can't tell who created the org or anything about it

**Comment by SingingBush** [comment]
That's so annoying. Maybe worth trying to contact github staff as it looks like someone's just trying to sit on it with no intention of usage.

**Comment by kingsleyh** [comment]
I think I will create dlang-Intellij instead

**Comment by Scellow** [comment]
Try to contact GitHub, they are open for that kind of stuff, plus that organization is not used at all

**Comment by SingingBush** [comment]
I sent github a message, it's worth seeing what they say

**Comment by SingingBush** [comment]
I got a reply from github, they've stated that the intellij-dlang group is not dormant. So we'll need to use an alternative.

**Comment by kingsleyh** [comment]
Ok well that's weird - who else could be using it and for what? Anyway I propose we use dlang-intellij instead

**Comment by russel** [comment]
I'd propose using something different. If the intellij-dlang organisation is actually active then using dlang-intellij as an organisation risks confusion between people wanting to find us and people wanting to find them.

We could go the alternative of being the intellij-plugin team under the dlang organisation. No risk of confusion there.

Perhaps before making a decision we could try and find out what intellij-dlang are. If the organisation has no repositories, what is it that makes them active. Or perhaps the GitHub person gave their response as the initial normal response to try and avoid having to do the formalities of a change of ownership?

**Comment by kingsleyh** [comment]
If we could find out who the owner is that might help. I'm not aware of any other IntelliJ D projects that are active - unless someone is working on a private repo - as there are no public repos.

It may also be unrelated to D - unlikely however.

Or it could be a deliberate obstruction by another IDE developer - on the forum a crazy guy who makes another IDE started trolling me and being rude in French last year or so.

Anyway all just supposition at this point - but it's going to be hard to avoid name collision / confusion.

Probably best to ignore other  D IntelliJ projects that are not as advanced as ours and just pick a name and move forward. We don't have a very big user base anyway so it's not a huge problem as long as we document our presence well and post on the forums etc

**Comment by kingsleyh** [comment]
How about an organisation name of DLanguage with a project called intellij-dlanguage or something like that?

**Comment by SingingBush** [comment]
@kingsleyh now that the repo is under the intellij-dlanguage organisation travis-ci will need to be changes to the new repo location and the environment variables for uploading builds to jetbrains will need adding again

**Comment by russel** [comment]
I guess we can close this issue now?
