### ISSUE TITLE
DCD autocompletion very unstable and underperforming

### ISSUE THREAD

**Issue by mbierlee** [intellij-dlanguage/intellij-dlanguage#200]
In none of my big projects DCD auto-completion works. When I try it with a fresh dub project it briefly works before stopping completely. Obviously close-by variables suddenly cannot be completed anymore.

Also auto-completion blocks entry, resulting in completion-as-you-type completely blocking the user from typing. This is very sub-optimal.

Lastly auto-completion stops working when there are syntax errors. Proper completion systems provide completions from partial ASTs. Though I reckon DCD is at fault here.

Even though using DCD is very convenient for IDE developers, it is not optimal at all. Relying on external processes to offer you fast completion is very inefficient. Ideally a custom completion provider is implemented within the plugin itself.

Environment:
IntelliJ IDEA 2017.1.4
Build #IC-171.4694.23, built on June 6, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10

D Language Plugin version 1.12

DCD client and server 0.8.0 built with DMD 2.070.0 and DUB 1.1.2

**Comment by pirocks** [comment]
Agreed. 
There exists in-plugin completion(although not very good completion), coming soon(like version 1.13), see issue #111.
Also I would recommend using dcd on a unix system, since in my experience that will have less random crashes. If you're interested in adding features/improving this plugin, I can answer questions about how everything works.

**Comment by mbierlee** [comment]
Definitely interested in picking this up. I will have to take some time to study the current project before being able to produce anything meaningful. I will keep the ticket open in case others will come here to report these issues.

**Comment by dmi7ry** [comment]
Need I specify path to sources somewhere? Because now for me it doesn't work absolutely (and I not found where I can specify SRCs paths).

Also when DCD defined in settings (D Tools paths), I have huge freezes during write a code.

**Comment by pirocks** [comment]
@dmi7ry  are you on version 1.13?

If you are you are you can define source paths like so:
![image](https://user-images.githubusercontent.com/10455020/29005446-a290ece6-7a90-11e7-8a2a-f4ca580e4e86.png)
![image](https://user-images.githubusercontent.com/10455020/29005447-a593181a-7a90-11e7-8a00-e76d5101128a.png)
I recommend doing both sourcepath and classpath which is why I have two screenshots.

When using the most recent dcd completion seems to work:
![image](https://user-images.githubusercontent.com/10455020/29005427-5f7aa802-7a90-11e7-8c98-9fcd7f2e094f.png)

Symbols that have a D icon next to there completion where completed by dcd, while symbols that do not where completed using builtin completion.

**Comment by pirocks** [comment]
@mbierlee since version 1.12 we have added builtin completion, which is likely much more reliable than DCD. It is not yet as good as DCD, however it is getting better. There where also some improvements to DCD support which may have fixed the issues you where experiencing.

**Comment by mbierlee** [comment]
With built-in completion now available and DCD being outside our control (and supposedly more stable now), I'm closing this issue. Focus on improving built-in completion is likely more desirable anyway.
