### ISSUE TITLE
Question about parser

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#205]
The bnf parser will/would take a lot of work to be made exactly perfect, and many future features require a good parser. I've noticed that in past branches this project used a parser from ddt. Is there a reason why it is no longer used, and would people be open to using a handwritten parser, which would be easier to compare with the dmd source?

**Comment by kingsleyh** [comment]
I tried to integrate the DDT parser in the past but it suffered massive performance issues as jetbrains make it almost impossible to integrate external parsers. So I moved to a BNF approach. However in my latest plugin - (purescript) I've opted for writing the parser by hand and it's actually much nicer - my main motivation was because purescript is whitespace sensitive which is really painful in BNF - so it was much easier to write a parser by hand. Purescript is a small language though so the parser is simple - D is massive - and at the time I didn't know how to write a parser. But I would definitely recommend giving a manual parser approach a go.

**Comment by pirocks** [comment]
Ok , I will try rewriting the existing parser by hand. And will comment back here with how it goes.

**Comment by pirocks** [comment]
So I've rewritten the parser, by hand by mostly copying the libdparse source in java. I still need to rework the Psi/PsiImpl classes, however the new handwritten parser seems better in every way(it's faster, has way better error recovery).I will probably submit a PR for it in 1-2 weeks.

**Comment by pirocks** [comment]
PR #216 adds a handwritten parser.
