### ISSUE TITLE
Timeline for next release?

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#208]
I was wondering if/when there was going to be a new release? I was also wondering about long term goals, priorities and wishlists, Lastly I was wondering how many people use the plugin on a daily basis, and if there would be any way of surveying them(Perhaps we could also implement the errorHandler extension point to get crash reports).See for more info about the errorHandler extension point: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206779605-Why-does-the-error-report-submitter-always-seem-to-be-greyed-out-

**Comment by SingingBush** [comment]
I've just merged all current changes into master, that should deploy a new eap build. I've been busy lately and not spent any time on this. If we're confident that current state of develop branch was good (all travis builds look good) then I guess we can tag a new release.

**Comment by SingingBush** [comment]
I've tagged [v1.13](https://github.com/intellij-dlanguage/intellij-dlanguage/releases/tag/v1.13) that should get deployed to the Jetbrains repo soon.

I have a few ideas about ways to improve the plugin. I've been doing some work on writing other plugins that depend on this one being installed. I like the idea of stripping all the dub related stuff into a standalone plugin so that this plugin can focus purely on the D language itself. I think going for a more modular approach will make it easier to maintain and also make it more likely that we could (in the long run) think about making a standalone IDE for D using the Intellij platform in the same way that their other IDE's do. We would bundle our own plugins for D, dub, SDLang, etc. We should arrange a time to discuss next steps.

For now though I think we should get rid of all DCD, dfmt, dscanner and get things working the intellij way.

**Comment by pirocks** [comment]
> For now though I think we should get rid of all DCD, dfmt, dscanner and get things working the intellij way.

Imho we should keep dfmt until we have formatting working, but I agree that we should get rid of dcd and dscanner.

**Comment by pirocks** [comment]
> We should arrange a time to discuss next steps.
Via gitter or something?

**Comment by SingingBush** [comment]
I think arranging a video call is best, I'm happy with Google hangout, Skype or anything really (as long as can access it from Linux or OSX). I'll message you my contact info on gitter.
