### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by unleashy** [intellij-dlanguage/intellij-dlanguage#245]
Hey, I really would want to use IDEA for D projects, and this plugin seems to need some work, so I thought "hey let's contribute to this" but I'm not too sure on where to start or if I can just complete some issues. 

Either way, I'd like some pointers from y'all if possible. Thanks!

**Comment by SingingBush** [comment]
there's a fair bit that needs doing. some tasks more tricky than others. first off it's worth reading [CONTRIBUTING.md](https://github.com/intellij-dlanguage/intellij-dlanguage/blob/develop/CONTRIBUTING.md) and familiarising yourself with the project. If you know anything about [JFlex](http://jflex.de/) that will help. Otherwise we have general [bugs](https://github.com/intellij-dlanguage/intellij-dlanguage/issues?q=is%3Aissue+is%3Aopen+label%3Abug), testing, [translations](https://github.com/intellij-dlanguage/intellij-dlanguage/issues?q=is%3Aissue+is%3Aopen+label%3Ai18n), documentation that's all needed.

It's worth joining the slack channel if you want to discuss anything off github https://intellij-dlang.slack.com

**Comment by unleashy** [comment]
Cool, cool, cool, thanks. I'll need an invite for the slack channel though. `eduardomfernandes@outlook.com`

**Comment by pirocks** [comment]
Issue #246 should be fairly straightforward, so it could make a good starter issue.

**Comment by mbierlee** [comment]
Could you enable invites on that slack workspace so anyone can join?

**Comment by SingingBush** [comment]
It only seems to have options for invitation only or to whitelist domains. I can send you an invite if you let me know your email.

**Comment by mbierlee** [comment]
Maybe a gitter channel is more accessible then?

**Comment by mbierlee** [comment]
Could you invite me? m.bierlee@lostmoment.com

**Comment by SingingBush** [comment]
@mbierlee done

**Comment by andre2007** [comment]
I think this issue can be closed?

**Comment by SingingBush** [comment]
agreed

**Comment by etienne02** [comment]
Can you invite me? `etienne.brateau@gmail.com`
