### ISSUE TITLE
DCD causes editor to hang

### ISSUE THREAD

**Issue by the-Mitu** [intellij-dlanguage/intellij-dlanguage#328]
Hello,

I know it's a known problem, but there seems to be no issue for it on GitHub.

Wouldn't DCD and other D tools be able to be run asynchronously? It is no problem that I have to wait a bit longer for the suggestion list - the only problem is that it hangs the editor and asynchronous execution of D tools could possibly solve it.

**Comment by pirocks** [comment]
Are you by any chance on windows, and compiled your dcd build yourself? If so try building with ldc, instead of dmd. 
Otherwise: 
I haven't really touched dcd integration recently, so this is probably a better question for other devs. Anecdotally I've noticed editor lag(see #256), but its been difficult too find the cause.  I suspect that integration with dcd/dscanner etc. is tricky, becuase intellij likes to kee track of what process/threads is reading/writing what files, and dcd/dscanner/ etc don't respect that.

**Comment by the-Mitu** [comment]
No, I am on Kubuntu 17.10 and have compiled nothing myself. Thanks for
response and I hope the issue can be solved somehow soon. :)

In case you need some more information, feel free to ask. :)

2017-12-13 12:56 GMT+01:00 Francis Nixon <notifications@github.com>:

**Comment by the-Mitu** [comment]
Oops, my mistake. I've built the DCD with dub indeed, I'm sorry. ;)
I'll try rebuilding it with GDB or LDC and report if it works better.

**Comment by pirocks** [comment]
What you build dcd with is only a problem on windows, so rebuilding
shouldn't change anything with kubuntu.

**Comment by the-Mitu** [comment]
You're right, it didn't change a thing :(

**Comment by andre2007** [comment]
Should be solved with https://github.com/dlang-community/DCD/pull/569

**Comment by SingingBush** [comment]
DCD integration should be a lot better in the next release
