### ISSUE TITLE
How to configure DCD server

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#356]
It is not clear for me, what should I insert in the DCD server flags field (settings). In the README.md it says I should enter the paths separated by comma. Quite below is a screenshot which uses spaces as separators instead of commas.

```C:\D\dmd2\src\druntime\import,C:\D\dmd2\src\phobos```

Both variants do not work for me. I still get errors for type "string" and so on. From the DCD README.md itself I got the impression I have to use ```-IC:\D\dmd2\src\druntime\import,-IC:\D\dmd2\src\phobos```
But this doesn't work either.

I think there are several things which could be improved:
- On windows, if file path C:\D\dmd2\ exists, the druntime and phobos path could be defaulted
- The command, how DCD server are invoked could be shown in the log

**Comment by pirocks** [comment]
> Both variants do not work for me. I still get errors for type "string"

Is your sdk defined? Under File > Project Structure > Project, you should make sure the project sdk is defined. When the project sdk is defined symbol resolution should work correctly. If your project sdk is defined check that its sourcepath contains the runtime and phobos. You should also be able to use alt enter when your cursor is hovering over an undefined symbol like string, and get a "Define Sdk" button.

> From the DCD README.md itself I got the impression I have to use `-IC:\D\dmd2\src\druntime\import,-IC:\D\dmd2\src\phobos` But this doesn't work either.

If the path to the dcd client and server is specified in Project>Other>DTools, dcd should just work, but is only used for code completion. Note that if building dcd yourself on windows you should use ldc instead of dmd, or use a pre-built binary.

**Comment by andre2007** [comment]
Thanks defining the sdk solved the problem.
