### ISSUE TITLE
Could you add logging facilities?

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#363]
I have several issues while using this plugin but it is quite hard to write a useful issues because all I see is, it doesn't work:
- endless loop while executing dunit tests
- performance issues while typing (DCD compiled with LDC)
- code completion doesn't work at all

I would like to write constructive issues but I am rather blind whats actually happening.
Could you maybe add logging messages and perhaps a log level setting to switch between verbose and quiet logs?

**Comment by SingingBush** [comment]
we use the logger provided by Intellij so if you start the IDE with logging set to info you should be able to get more information about what the plugin is doing in the idea.log which should be located in `%home%\.IntelliJIdea2017.3\system\log\idea.log` on windows.

**Comment by pirocks** [comment]
This plugin does log warning etc. if something is very wrong. Logfiles an be found under Help > Show Log (maye be called something slightly different depending on platform/intellij version). There isn't much debug logging, mostly logging of exceptions etc.

> performance issues while typing (DCD compiled with LDC)

DCD is currently being reworked. Performance issues are likely caused by the way intellij handles saving files.  

>code completion doesn't work at all. 

Will probably be fixed in next version. If not make an issue, with screenshots of your settings and os version information.

>endless loop while executing dunit tests

As far as I know d-unit hasn't been touched in years. I don't really know the details of how it works.

**Comment by SingingBush** [comment]
I'm intending to take a look at adding some features around testing as part of https://github.com/intellij-dlanguage/intellij-dub

**Comment by andre2007** [comment]
Thanks a lot. I will have a look at the logs and check whether I can create detailed error descriptions.
I will close this issue.
