### ISSUE TITLE
NullPointerException in GdbMiValue.toString

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#444]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/561351695/

```
NullPointerException: None
    at uk.co.cwspencer.gdb.gdbmi.GdbMiValue.toString(GdbMiValue.java:79)
    at java.lang.String.valueOf(String.java:2994)
    at java.lang.StringBuilder.append(StringBuilder.java:131)
    at uk.co.cwspencer.gdb.gdbmi.GdbMiResult.toString(GdbMiResult.java:56)
    at java.lang.String.valueOf(String.java:2994)
...
(11 additional frame(s) were not displayed)
```

**Comment by andre2007** [comment]
If I remember correctly this kind of error occurs in case of any error. E.g. if you try to debug a app in coff format using MagoMI without having mago remote executable on your system and having a regedit entry pointing to this mago remote executable and having dia140 dll registered via regserv32. There are many reasons.... which could cause this error.Could you describe what you have done to get this exception?

**Comment by pirocks** [comment]
Since this is a sentry reported bug I have no idea how this happened. It was reported by a user using the IDE error reporter.

**Comment by pirocks** [comment]
Plugin version is 1.17
GDB version is GNU gdb (mago-mi 0.3.3) 7.1.90

**Comment by andre2007** [comment]
Thanks, now I understand what these sentry issues are all about.

**Comment by SingingBush** [comment]
wow `uk.co.cwspencer.gdb.gdbmi.GdbMiValue` has a fair few potential null pointers. I'm weary of a lot of that gdb code and would really like to see it separated out and maintained in https://github.com/intellij-dlanguage/intellij-gdb either for us to use as a dependency or for it to be an optional plugin. Because CLion and Appcode should already have some kind of GDB integration. For now I've put a quick null check in the _toString()_ method but will keep this issue open as I've not looked into the actual cause (I suspect it's possible because it has a nullary constructor that is called from _GdbMiResult_).
