### ISSUE TITLE
Not clear how to configure D compiler in CLion

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#464]
When creating a new project in CLion(as shown below), it is not clear how to configure a compiler/sdk. Perhaps there should be an "Add SDK" button. Similarly, there appears to be no way to configure dub.

![image](https://user-images.githubusercontent.com/10455020/43031367-57f5328c-8c55-11e8-95b6-818604999f99.png)

**Comment by SingingBush** [comment]
I've done some initial work to allow CLion users to configure the DMD path in the settings menu:

![clion - d settings screenshot](https://user-images.githubusercontent.com/870567/51445513-d6597000-1cfd-11e9-8231-d8504787cd36.png)
It's work in progress. I'll push when functional (in a new branch) so anyone interested can try it out.

**Comment by SingingBush** [comment]
quick update on this. I've made some progress on this but it's been slow. Partly due to other commitments but also due to lack of CLion plugin docs and considering how to this properly. Supposedly although `com.intellij.openapi.projectRoots.Sdk` is available in all products it's not really supposed to be used in CLion. 

CLion has the concept of Toolchains so I'd expect to be able to define a D Toolchain but the code hasn't been done in a way that allows for this (perhaps @amakeev can shed some light on this). I've looked at:

 - application service to hold the state of the toolchain config: `com.jetbrains.cidr.cpp.toolchains.CPPToolchains()`
 - the config page for the toolchains `com.jetbrains.cidr.cpp.toolchains.CPPToolchainsConfigurable()`
 - additional `com.jetbrains.cidr.toolchains.CidrExecutableTool` for things like CMake & GDB, maybe we use this for dub

As a side note; for anyone else trying to make CLion support better, in the build.gradle file set `type 'CL'` and the idea version to at least 2018.3.4 to get CLion jars working to the point that you can at least import the above classes.

**Comment by amakeev** [comment]
@SingingBush Not sure I got the question right, but probably the `CPPToolchain` is not needed for D.
You can take a look at [Swift|https://plugins.jetbrains.com/plugin/8240-swift] and [Rust|https://plugins.jetbrains.com/plugin/8182-rust] plugins as examples, they both use their own compiler and toolchain settings.
![image](https://user-images.githubusercontent.com/238583/53737335-8937f480-3e8c-11e9-8e66-a89ce2dfd732.png)

**Comment by SingingBush** [comment]
@amakeev I was expecting a common interface or abstract class that would be needed for handling toolchains.
I've taken a look at [intellij-rust/src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt](https://github.com/intellij-rust/intellij-rust/blob/f3f065f3b624d6037758a23f3b78168612466e19/src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt) so will use that as an example. Is there source available for the [swift plugin](https://plugins.jetbrains.com/plugin/8240-swift)?

**Comment by amakeev** [comment]
No, I'm afraid Swift is closed-sourced. There is also a [Fortran plugin|https://plugins.jetbrains.com/plugin/9699-fortran] for CLion, but I believe it uses default C++ toolchains.

**Comment by sannysanoff** [comment]
Clion 2019.2.1, no "D Compiler" in settings, only "D Tools". Can't compile, anything.

**Comment by SingingBush** [comment]
These changes are still sat on a branch on my local machine. I need to find the time to pick it up again

**Comment by SingingBush** [comment]
This is now essentially sorted but won't be truly complete until #465 and #541 are finished

![CLion - new D Application](https://user-images.githubusercontent.com/870567/98125909-e3ccf380-1eac-11eb-98af-2f40b5c62b4e.png)
