### ISSUE TITLE
Completely unusable on Ubuntu due to missing libraries

### ISSUE THREAD

**Issue by barsan-md** [intellij-dlanguage/intellij-dlanguage#476]
There is no way for me to make it work on Ubuntu 18.04. I installed everything needed (dub, dmd, ldc2, ...) and verified that builds and runs perfectly. The plugin is unusable at this stage because of lots of "DScanner Error" for missing stuff.
As a solution I started adding stuff into the "Sourcepath"
```
file:///usr/include/dmd/phobos
file:///usr/include/dmd/druntime/import
file:///usr/lib/ldc/x86_64-linux-gnu/include/d/core
file:///usr/lib/ldc/x86_64-linux-gnu/include/d/ldc
```
I am not even sure what must be added (I am completely beginner to Dlang).

I have the feeling though that I could never manage to solve it because it asks for some stuff that shouldn't be needed (for example `Could not resolve location of module 'core/sys/netbsd/sys/mman'`, why sould I have netbsd stuff).

Does anybody use this plugin on linux successfully?

**Comment by andre2007** [comment]
First step to solve this issue is to find out whether it is related to IntelliJ D plugin or D-Scanner.

Could you execute D-Scanner directly on the shell for your project and check whether you get it working here without the mentioned issues?

If yes, please add this command to the github issue and also the Sourcepaths determined by IntelliJ.

PS at the moment, there is no log written by IntelliJ how D-Scanner was called. This should be added for problem analysis. I will create a pr the next days.

**Comment by barsan-ds** [comment]
Ok, after a lot of tries I managed to make it work by using this repository, instead of downloading the single executables of D tools from the various github repos.
http://d-apt.sourceforge.net/

**Comment by SingingBush** [comment]
@barsan-md For the phobos/druntime paths we had to make some assumptions on location. I use Fedora so my focus is on making sure the plugin works with the paths that are used by the rpm install. I think that's the same for the Ubuntu packages that are in that sourceforge repo.
There's quite a bit of work needed around the D Tools.
