### ISSUE TITLE
Release changes in develop?

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#479]
I've been out of the loop for a while. I know there's still many issues to fix but is it worth releasing in the current state? 
If a couple of regulars confirm, I'll endeavour to do it over the weekend. It'd also be good if someone else wants to be able to release. I'm not likely to get much time on it before new year.

**Comment by SingingBush** [comment]
Before doing a [1.17.2](https://github.com/intellij-dlanguage/intellij-dlanguage/milestone/13) release #372 and #404 should be fixed. The rest could be moved back to [1.17.3](https://github.com/intellij-dlanguage/intellij-dlanguage/milestone/14)

**Comment by SingingBush** [comment]
been too many releases since last looked at this. Api has breaking changes for 2018.3 and again for 2019.1

am going to just clean up what's been done and release 2 builds. one for 2018.1.3 - 2018.2.* and another for 2018.3.* then any other work can be done on the newer 2019 API

**Comment by andre2007** [comment]
The just released tag has a wrong version (2013.3) in the description. 
While releasing new versions could you also create a forum post on the dlang announce group? I think this plugin is not well known and release announcements are a good opportunity to make some noise.

**Comment by SingingBush** [comment]
pants, can't believe I did that. I used to post on forum but I find a lot of the posts there a little negative. 
There's still a ton of work needed to get this plugin have a decent user experience so maybe not worth making too much noise about it yet. The whole DCD thing is a problem, I've been trying to get that workspace-d PR rebased and working but it needs work.

**Comment by andre2007** [comment]
I use it for my daily work and I am very satisfied. For me there is only one serious issue which might be a showstopper for other users. For creating and copying modules I have to leave the IDE and use the Windows explorer due to some bugs.

Dcd issue is due to missing exception handling in dcd. Exceptions are propagated to the console. As the option to hide the console is set during compilation of dcd, exceptions are shown as Windows dialogs. This is an issue for IntelliJ as it waits forever for the end if dcd. 
A simple catch all exceptions in dcd would solve the issue.
