### ISSUE TITLE
Plugin is incompatible with current IntelliJ IDEA version

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#503]
![image](https://user-images.githubusercontent.com/1451047/61846020-ce91a880-aea5-11e9-8cb1-27a577b13900.png)

**Comment by 8ctopus** [comment]
For those who can't wait for the update, I've managed to install it in the latest version of the IDE 2019.2 by editing the following line in DLanguage-1.19.jar\META-INF\plugin.xml (using 7zip)

from:
<idea-version since-build="191" until-build="191.*"/>

to:
<idea-version since-build="192" until-build="192.*"/>

**Comment by andre2007** [comment]
Thanks for the tipp:)

**Comment by SingingBush** [comment]
It's not as simple as that. Pull current develop branch and run it against 2019.2, code changes are required

**Comment by andre2007** [comment]
Last working version is 2019.1.4. It can be downloaded from here
https://www.jetbrains.com/idea/download/other.html

**Comment by zoujiaqing** [comment]
> It's not as simple as that. Pull current develop branch and run it against 2019.2, code changes are required

Please release one new version to support 2019.2, thanks.

**Comment by pirocks** [comment]
As of 2ad9d523a7eef0d4885f08443dd11499271735b8 develop is now compatible with 2019.2.

**Comment by SingingBush** [comment]
Am going ahead with release. If there's bugs we'll just have to deal with them. At least we can just focus on 2019.2 now
