### ISSUE TITLE
Develop build fails

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#534]
Using master 582a791addddf6d6cb626c4456bdcf670520c17f having executed `./gradlew clean` and `rm -rf .gradle`, `./gradlew buildPlugin` results in a build fail in task `:buildSearchableOptions`
```
2019-11-06 09:14:05,606 [   2530]  ERROR - openapi.options.ConfigurableEP - While loading class io.github.intellij.dlanguage.utils.GuiUtil: io/github/intellij/dlanguage/utils/GuiUtil has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 55.0 [Plugin: net.masterthought.dlanguage] 
com.intellij.diagnostic.PluginException: While loading class io.github.intellij.dlanguage.utils.GuiUtil: io/github/intellij/dlanguage/utils/GuiUtil has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 55.0 [Plugin: net.masterthought.dlanguage]
```

**Comment by SingingBush** [comment]
I had problems the other day with _buildSearchableOptions_. The error you're seeing is to do with Java version and has been mentioned on https://github.com/JetBrains/gradle-intellij-plugin/issues/382, at the time my problem was due to line endings on the Windows machine I was using https://github.com/JetBrains/gradle-intellij-plugin/issues/437

In fact there's a lot of issues related to that part of the gradle-intellij-plugin:
https://github.com/JetBrains/gradle-intellij-plugin/issues?utf8=%E2%9C%93&q=is%3Aissue+buildSearchableOptions

The travis builds are working (Ubuntu and JDK8). What system and JDK are you using?

**Comment by russel** [comment]
I believe I am using Debian Sid with OpenJDK11, but there are three JDKs available, my OpenJDK11, JetBrains JDK11 (four versions as I have CLion, GoLand, IntelliJ IDEA, and Pycharm, and my OpenJDK13. If OpenJDK13 was being used the version number would be 57 so the fact that 55 and 56 are the numbers implies something really weird is going on – 55 is OpenJDK11 and 56 is OpenJDK12 which is no longer available on Debian Sid and not present on my laptop.

**Comment by SingingBush** [comment]
For now the project should be targeting Java 1.8 and if building correctly that will be fine on the latest IDE's which ship with a bundled JDK 11. Make sure that if you do `./gradew --version` that it's picking up a JDK 8 otherwise you need to correct your JAVA_HOME variable.

If that doesn't work then maybe worth trying an older gradle-intellij-plugin in case the changes it introduced to use the JB Java are somehow messing things up.

**Comment by SingingBush** [comment]
I just tried `./gradlew clean runIde` on my Linux machine at it built/ran fine. The output of `./gradlew --version` for me is:

```
------------------------------------------------------------
Gradle 4.8.1
------------------------------------------------------------

Build time:   2018-06-21 07:53:06 UTC
Revision:     0abdea078047b12df42e7750ccba34d69b516a22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_232 (Oracle Corporation 25.232-b09)
OS:           Linux 5.3.8-300.fc31.x86_64 amd64
```

Did you get time to try it again with JDK 8?

**Comment by russel** [comment]
Hummm… I installed OpenJDK8 and it all worked. So I tried again with OpenJDK11 and it now works. This is weird.

I appreciate that JDK8 has to be the base version for distributions generally since JetBrains still issue IDEs with JDK8. However I think I'll persevere building with JDK11 for myself since all my JetBrains IDEs are the ones on JDK11.

**Comment by SingingBush** [comment]
that may have been ok as it wouldn't have recompiled unless there were code changes so the classes that were built with JDK 8 were still working. We cannot target Java 11 until it's the min supported Java version in Intellij. 

I'll add some travis-ci jobs for building with JDK 11 though: #535

**Comment by russel** [comment]
I believe I did `gradle-on-8 clean; gtradle-on-11 clean` between the JDK8 build and the JDK11 build, but I haven't investigated the Gradle build enough to know if it did what I think it did!

**Comment by russel** [comment]
Hummm… I installed OpenJDK8 and it all worked. So I tried again with OpenJDK11 and it now works. This is weird.

I appreciate that JDK8 has to be the base version for distributions generally since JetBrains still issue IDEs with JDK8. However I think I'll persevere building with JDK11 for myself since all my JetBrains IDEs are the ones on JDK11.
