### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by RUSshy** [intellij-dlanguage/intellij-dlanguage#559]
Hi

Is there a roadmap for this plugin?

What is the current state of D with intellij?

Debugging with CLion is possible?

Integration with DLS?

I'm still looking forward to using IDEA based IDE for D, but so far it is very annoying

**Comment by SingingBush** [comment]
There's been features that I've wanted to add to the plugin for years but right now it's hard enough keeping up with the evolution of the Intellij platform and the various bugs that get reported. CLion is not properly supported yet. DLS is same as it was last year #487 

It is frustrating that D support in Intellij is not great. There's simply not enough people interested in working on it. That's why I started contributing to this project. It doesn't help that the learning curve for custom language support in Intellij is fairly high and much of the functionality in this project requires manual testing

**Comment by SingingBush** [comment]
For anyone wanting to pick up issues. The main things to work on are:

- bug fixes & compatibility with latest Intellij versions
- CLion support (should also cover AppCode)
- performance tweaks
- Documentation - on https://intellij-dlanguage.github.io/

**Comment by SingingBush** [comment]
v1.24 has been uploaded to the plugin repo to support Intellij 2020.1 today:
https://plugins.jetbrains.com/plugin/8115-d-language/versions

Any help/feedback about the plugin on that version will be helpful.

**Comment by russel** [comment]
1.24 working so far for me on CLion 2020.1

**Comment by SingingBush** [comment]
for bullet point 4 that I made in March I've started getting some wiki pages together : https://github.com/intellij-dlanguage/intellij-dlanguage/wiki initially just pulling some sections from the readme and https://intellij-dlanguage.github.io/

There's a mountain of bugs building up that I simply do not have enough time to deal with alone so any help is appreciated
