### ISSUE TITLE
gdb compiled path on windows

### ISSUE THREAD

**Issue by chuwak** [intellij-dlanguage/intellij-dlanguage#560]
when I try to use GDB on windows I have next errors

http://prntscr.com/rvmnkn

![d_gdb_win_err](https://user-images.githubusercontent.com/6860606/78823795-f5691e00-79e5-11ea-86c1-4228f80652f3.png)

slashes just gone.
I tryed 2 versions of  GDB 7.4 and 8.0.1  and result the same.

and I cannot change any parameters in gdb "flags"  field
it seems it does not change anything

**Comment by SingingBush** [comment]
Some more defensive code could be in the _uk.co.cwspencer.*_ package or _io.github.intellij.dlanguage.run.RunUtil_ but the root of the problem is likely down to *io.github.intellij.dlanguage.run.RunAppRunner*. Note the _todo_ comment that is already in there:

```
return RunUtil.startDebugger(this, state, env, project, executor, dlangRunAppState.getExecutableCommandLine(dlangRunAppState.getConfig()).getExePath());//todo this is yucky
```

I'm not using Windows so much at the minute so would be good to have someone debug it / fix it and make a merge request

**Comment by SingingBush** [comment]
@chuwak please check out the develop branch and run the project from source `./gradlew runIde`. The fix will go out in the next release
