### ISSUE TITLE
Syntax highlighting doesn't work as in the readme

### ISSUE THREAD

**Issue by SizeableMilkProduct** [intellij-dlanguage/intellij-dlanguage#593]
**Desktop (please provide environment info):**
 - OS: Windows 7
 - IDE: Intellij 2020.2
 - Plugin Version: 1.25

**D compiler and tools (please provide version numbers):**
 - dmd: 2.093.1
 - dub: 1.22.0
 - dcd: 1.13.1
 - dscanner: 0.11.0

**Describe the problem**
Judging from the readme, Syntax Highlighting should be able to change things like function definition. However changing the color doesn't change anything in a code file. In the screenshots there are are also more settings to change the colors of.
I made a screenshot of all the settings I have for D files and there are some missing there if you compare it with the screenshot in the readme. Also observe how I changed Function Definition color but it didn't change in the code file behind the settings window.

Might be something between the Mac version and Windows version of Intellij but I thought they should work exactly the same.

**Screenshots**
![BugIntellij](https://user-images.githubusercontent.com/19991155/93531934-ee9cea80-f937-11ea-8b9c-ce36460698cd.PNG)

**Comment by g5becks** [comment]
> Might be something between the Mac version and Windows version of Intellij but I thought they should work exactly the same.
Not working for me on ubuntu either

**Comment by rez23** [comment]
me too on windows highlight parsing is totally broken. the most of keyword result as default text in general.

**Comment by SingingBush** [comment]
The syntax highlighting is really in need of some tlc. Due to the shear number of other issues it's been overlooked for far too long. If someone wants to help in this are then it's worth taking a look at `io.github.intellij.dlanguage.colors.DColor.kt` and the example D file (`src/main/resources/settings/color_page.d`) that's used when updating values in the settings menu.

It's also worth taking a look at `com.intellij.ide.highlighter.JavaHighlightingColors` as an example but please don't use any values contained in that class as it's not available across all Jetbrains IDE's.
