### ISSUE TITLE
Intellij hangs after configuring dub

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#684]
**Desktop (please provide environment info):**
 - OS: Fedora 36
 - IDE: Intellij 2022.1
 - Plugin Version 1.27.2

On a fairly fresh install of Intellij, after installing D plugin I was unable to setup dub. The IDE hung after autofinding the binary:
![intellij-dlanguage-setup-dub](https://user-images.githubusercontent.com/870567/170990122-94113ae4-4350-4568-ae67-c0c12652a754.png)

**Comment by SingingBush** [comment]
It appears that the crucial thing here was that the compiler was not setup. It really shouldn't make a difference but after I restarted the IDE I added dmd as an SDK (in a non-D project) then setup dub. It worked fine that way round.

**Comment by SingingBush** [comment]
Although better, it seems this is still possible with version 1.28.1 of the plugin. I ended up in this situation when setting up dub during local testing, I suspect there is some kind of race condition because when this happened I was setting things up pretty quickly. After terminating the IDE process and rebooting I was able to configure dub by not rushing through the UI

**Comment by etienne02** [comment]
I success to have my IDE in debug move frozen, it’s because I clicked on "OK" during the update of the field.
![image](https://user-images.githubusercontent.com/9578950/176325463-16184e6f-4d32-4e70-ba8c-4cf592224137.png)
As you can see in the image it deadlock during the settext of the field. 
I think that the fix would be to override `disposeUIResources()` to stop all threads or at least wait that they finished
