### ISSUE TITLE
Syntax highlighting for string randomly stopped working

### ISSUE THREAD

**Issue by therealbluepandabear** [intellij-dlanguage/intellij-dlanguage#815]
The syntax highlighting for `string` randomly bugged out and stopped working:

![image](https://user-images.githubusercontent.com/50536495/210899672-e28bd4c3-c3d0-4f4d-8a79-5a3a16f69b62.png)

It stopped working for that specific file only, weird.

Tried to invalidate caches, doesn't fix it.

I have also noticed that syntax highlighting for `string` is sometimes slow (up to 3x slower) compared to `int`.

**Comment by etienne02** [comment]
For the slowness it’s normal. Due to the fact that string is not a language keyword, It’s not process like this in the lexer. And it’s an annotator that will highlight it (on a second pass, at the same time as annotations). So it’s highlighted few time after other keywords (like int).
For the highlight stop working, I don’t know, can you add an annotation (like @test) somewhere to see if it’s in yellow or not?
If it’s colored, there is an issue in the annotator, if not, the annotator did not started, so it’s a platform issue (and I’m not sure to be able to do a fix).

**Comment by therealbluepandabear** [comment]
> For the slowness it’s normal. Due to the fact that string is not a language keyword, It’s not process like this in the lexer. And it’s an annotator that will highlight it (on a second pass, at the same time as annotations). So it’s highlighted few time after other keywords (like int). For the highlight stop working, I don’t know, can you add an annotation (like @test) somewhere to see if it’s in yellow or not? If it’s colored, there is an issue in the annotator, if not, the annotator did not started, so it’s a platform issue (and I’m not sure to be able to do a fix).

Ok, I will get back soon.

**Comment by therealbluepandabear** [comment]
It's happening in the latest version, but this happened only once so I doubt it's worth wasting time trying to fix this, I'll close this issue for now.
